35 support specific iiif properties as geojson properties
CenterForDigitalHumanities/navplace-viewer pull request #46
Opened 2024-03-02 19:29 UTC by tobradovic

Support has been added for the `requiredStatement` and the `rights` IIIF properties.

The `requiredStatement` property appears at the top of popups when viewing the resource.
The `rights` property appears under the thumbnail in the popups.

Support for more properties will be added during the second half of the sprint.

2024-03-18 22:12 UTC, thehabes requested changes
You should also detect the `navDate` property as well

This one has more baggage than I anticipated so let's make sure not to scope creep.

Use this object which as `navPlace` on a Canvas.  The "rights" URI does not appear and it should.
- ?iiif-content=https://store.rerum.io/v1/id/65f8b628d1cb2cde1dc34573

Note that values can be HTML.  You don't have to worry about that, but here's that same example but the values had HTML in them.  Notice the difference in rendering.  There's nothing we can really do about it, this is just fun to see.
-   ?iiif-content=https://store.rerum.io/v1/id/65f8b36dd1cb2cde1dc34571

Here is a Collection and a Manifest to use to test as well
- ?iiif-content=https://store.rerum.io/v1/id/65f8b83fd1cb2cde1dc34575
- ?iiif-content=https://store.rerum.io/v1/id/65f8b666d1cb2cde1dc34574

For the scope of this PR, make sure you include support for `navDate`.  Make sure that "rights" appears in the pop up for Canvases, I am not sure why it won't.  Have the order of properties be the following.

1. label
2. summary
3. navDate
3. thumbnail with rights
4. required statement

**This may be too noisy to do by default.**  
For further consideration (outside of your scope) consider how noisy this makes the pop up.  It isn't always very clear what each section is and which ones are important.  Maybe there needs to be an option to "show more metadata" that user can choose and in doing so can expect noisier pop ups.  

![image](https://github.com/CenterForDigitalHumanities/navplace-viewer/assets/3287006/f0d0712d-4306-4b95-b449-36b5e2af4656)

![image](https://github.com/CenterForDigitalHumanities/navplace-viewer/assets/3287006/d5ded735-58f2-4032-9dfa-4763817acaa0)

2024-04-17 03:11 UTC, tobradovic commented
Sample popup with navDate property:

![Screenshot 2024-04-16 220914](https://github.com/CenterForDigitalHumanities/navplace-viewer/assets/144740070/701d0a58-e450-44b5-bc9d-a0b9d1889210)

2024-04-22 21:22 UTC, thehabes approved these changes
Very nice and thank for you the clean code.  This grabs the properties I expected it to, and I tested it against all test objects noted in the previous review.  I did not encounter any errors related to pop-up generation.

2024-04-22 21:34 UTC, yashaswini-slu approved these changes

2024-04-22 21:34 UTC, merged